# Generated by Django 5.2.9 on 2025-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_create_trouble", "0002_basemodel_childmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ManyToManyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "many_to_many",
                    models.ManyToManyField(to="bulk_create_trouble.onemodel"),
                ),
            ],
        ),
    ]
