# Generated by Django 5.2.9 on 2025-12-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic_foreign_key_model", "0007_alter_genericforeignkeymodel_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericforeignkeymodel",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["blog", "author"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
