# Generated by Django 5.2.9 on 2025-12-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("a_model", "0001_initial"),
        ("b_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="a1model",
            name="fieldB",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="b_model.b1model"
            ),
        ),
    ]
