# Generated by Django 5.2.8 on 2025-12-05 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("author.author",),
        ),
    ]
