# Generated by Django 5.2.9 on 2025-12-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("a_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="B1Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fieldA", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="B2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fieldA", models.CharField(max_length=100)),
                (
                    "fieldB",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a_model.a1model",
                    ),
                ),
            ],
        ),
    ]
