# Generated by Django 5.2.9 on 2025-12-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("bio", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["first_name"], name="data_optimi_first_n_b48ea3_idx"
                    )
                ],
            },
        ),
    ]
