# Generated by Django 5.2.9 on 2025-12-06 08:01

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitorPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("state", django_fsm.FSMField(default="応募中", max_length=50)),
            ],
        ),
    ]
