# Generated by Django 5.2.9 on 2025-12-06 23:07

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fsm_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitorpost",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("applying", "応募中"),
                    ("won", "当選"),
                    ("lost", "落選"),
                    ("not_selected", "不採用"),
                    ("withdrawn", "辞退"),
                ],
                default="applying",
                max_length=50,
            ),
        ),
    ]
